# config for https://travis-ci.org/aisapatino/sjfnw

language: python
python:
  - "2.7"

# disable sudo to let travis run in container
sudo: false

# only send emails for new failures
notifications:
  email:
    on_success: never
    on_failure: change

install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip
  - unzip -q google_appengine_1.9.40.zip
  - pip install codecov
  - pip install -r requirements.txt -t libs

before_script:
  - export PATH=$PATH:$PWD/google_appengine
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine/lib/webob-1.2.3
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine/lib/yaml/lib

# run tests with coverage
script: ./scripts/coverage skip-html

# send coverage to coveralls if tests passed
after_success: codecov
