#!/usr/bin/env bash

# cd into scripts dir to avoid bug - see pylint_exec for more info
cd "$(dirname "$0")"

# run python linter on the whole project
./pylint_exec --rcfile=../.pylintrc ../sjfnw

# run javascript linter (configured by .eslintrc)
#eslint sjfnw/static/js/*.js
