#!/usr/bin/env python

# Pylint executable

# Workaround to avoid pylint_plugin_utils.NoSuchChecker error due to comparing
# <class 'libs.pylint.checkers.base.NameChecker'> to
# <class 'pylint.checkers.base.NameChecker'>
#
# Astroid does some weird stuff with loading modules that adds the "libs" there.
# Simplest workaround while still being able to run lint from the project root
# is to use a pylint exec outside of sjfnw/libs/pylint (or a parent directory)
# that is also called from outside those dirs

# Thus we have this script + the lint script that calls it

import os
import re
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '../libs/dev'))

import pylint

if __name__ == '__main__':
  sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
  sys.exit(pylint.run_pylint())
